# Generated by Django 6.0.5 on 2026-05-29 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "isbn",
                    models.CharField(max_length=13, primary_key=True, serialize=False),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("area_conocimiento", models.CharField(max_length=100)),
                ("ejemplares_disponibles", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Libro",
                "verbose_name_plural": "Libros",
            },
        ),
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identificacion_usuario", models.CharField(max_length=50)),
                ("fecha_prestamo", models.DateField(auto_now_add=True)),
                ("fecha_vencimiento", models.DateField()),
                (
                    "estado",
                    models.CharField(
                        choices=[("ACTIVO", "Activo"), ("DEVUELTO", "Devuelto")],
                        default="ACTIVO",
                        max_length=10,
                    ),
                ),
                (
                    "isbn",
                    models.ForeignKey(
                        db_column="isbn",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="prestamos.book",
                    ),
                ),
            ],
            options={
                "verbose_name": "Préstamo",
                "verbose_name_plural": "Préstamos",
            },
        ),
    ]
